'use strict';
// Original procedural pixel sprites and synthesized audio. No ROM or external assets.
(() => {
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const overlay=document.querySelector('#overlay'),msg=document.querySelector('#message'),start=document.querySelector('#start');
const W=480,H=640,keys=new Set();
const sprites={
 ship:['000010000','000121000','000121000','010121010','012121210','112121211','122222221','110121011','100010001'],
 bee:['010000010','001000100','003303300','033333330','113333311','111333111','010333010','010101010'],
 butterfly:['100000001','110000011','122101221','122212221','011222110','001222100','012101210','110000011'],
 boss:['001000100','011101110','122222221','122121221','112222211','011222110','001111100','011000110','110000011']};
const palettes={ship:['','#e8f5ff','#ef424f'],bee:['','#ffd34c','#ed485b','#58b7f5'],butterfly:['','#ec435d','#7895ff'],boss:['','#44d99d','#87f1d4']};
function sprite(c,type,x,y,scale=3,angle=0,damaged=false){c.save();c.translate(x,y);c.rotate(angle);const a=sprites[type],p=damaged?['','#8990ff','#d1aeff']:palettes[type];for(let r=0;r<a.length;r++)for(let q=0;q<a[r].length;q++){const v=+a[r][q];if(v){c.fillStyle=p[v];c.fillRect((q-a[r].length/2)*scale,(r-a.length/2)*scale,scale,scale)}}c.restore()}
document.querySelectorAll('[data-sprite]').forEach(c=>sprite(c.getContext('2d'),c.dataset.sprite,33,24,4));
let audio,muted=false;function sound(f=440,d=.08,type='square',slide=.5){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*slide),audio.currentTime+d);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
let best=0;try{best=Number(localStorage.getItem('galaga-best-v1'))||0}catch{}
let state='title',score=0,stage=1,lives=3,player,foes=[],shots=[],bullets=[],particles=[],captured=null,clock=0,stageTime=0,fireTime=0,attackTime=0,clearTimer=0,bonus=false,bonusHits=0,extraAt=20000,banner='',bannerTime=0,shake=0;
const stars=Array.from({length:95},()=>({x:Math.random()*W,y:Math.random()*H,s:Math.random()*1.7+.3,color:['#76b4d7','#ebcf92','#a971c1','#66758b'][Math.floor(Math.random()*4)]}));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function announce(t,d=2){banner=t;bannerTime=d}
function newPlayer(){player={x:240,y:575,dual:false,inv:3,dead:0}}
function wave(){foes=[];shots=[];bullets=[];stageTime=0;clearTimer=0;attackTime=4;bonus=stage%4===3;bonusHits=0;announce(bonus?'CHALLENGING STAGE':`STAGE ${stage}`,2.7);
for(let i=0;i<40;i++){let row=Math.floor(i/8),col=i%8;foes.push({id:i,type:row===0?'boss':row<3?'butterfly':'bee',hp:row===0&&!bonus?2:1,x:-50,y:-50,homeX:93+col*42,homeY:108+row*36,mode:'waiting',delay:Math.floor(i/8)*1.25+(i%8)*.11,t:0,side:i%2?1:-1,shot:false,carry:false,angle:0})}}
function begin(){score=0;stage=1;lives=3;captured=null;particles=[];extraAt=20000;clock=0;newPlayer();wave();state='play';overlay.hidden=true;document.querySelector('#pause').textContent='일시정지';sound(440,.3,'triangle',2)}
function addScore(n){score+=n;if(score>best){best=score;try{localStorage.setItem('galaga-best-v1',String(best))}catch{}}while(score>=extraAt){lives++;extraAt+=70000;announce('EXTRA FIGHTER',1.5);sound(880,.4,'triangle',2)}}
function boom(x,y,color='#ffc86b'){shake=3;for(let i=0;i<20;i++){const a=Math.random()*Math.PI*2,v=Math.random()*120+25;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,t:.5+Math.random()*.3,color})}sound(140,.17,'sawtooth',.2)}
function hurt(){if(player.inv>0||player.dead>0||state!=='play')return;boom(player.x,player.y);if(player.dual){player.dual=false;player.inv=2;return}lives--;player.dead=1.6;if(lives<=0){state='over';msg.textContent=`GAME OVER\n점수 ${score.toLocaleString()} · 스테이지 ${stage}`;start.innerHTML='다시 출격 ↗';overlay.hidden=false}}
function hit(e){e.hp--;if(e.hp>0){sound(240,.09);return}e.mode='gone';boom(e.x,e.y,e.type==='boss'?'#62f5b2':'#ffa45b');if(bonus)bonusHits++;addScore(bonus?100:e.type==='boss'?(e.diving?400:150):e.type==='butterfly'?(e.diving?160:80):(e.diving?100:50));
if(e.carry&&captured){if(e.diving){player.dual=true;player.inv=2;announce('DUAL FIGHTER!',2);sound(600,.5,'triangle',2)}else{announce('CAPTURED FIGHTER LOST',2)}captured=null}}
function fire(){if(player.dead>0||shots.length>=(player.dual?4:2))return;for(const dx of player.dual?[-14,14]:[0])shots.push({x:player.x+dx,y:player.y-15});sound(950,.07,'square',.35)}
function aim(e){const dx=player.x-e.x,dy=player.y-e.y,l=Math.hypot(dx,dy);const v=130+Math.min(stage*9,85);bullets.push({x:e.x,y:e.y,vx:dx/l*v,vy:dy/l*v})}
function formation(e){return{x:e.homeX+Math.sin(clock*.9)*17,y:e.homeY+Math.sin(clock*1.2)*4}}
function dive(e,tractor=false){e.mode=tractor?'tractor':'dive';e.t=0;e.sx=e.x;e.sy=e.y;e.target=player.x;e.shot=false;e.diving=true}
function update(dt){clock+=dt;stars.forEach(s=>{s.y+=s.s*22*dt;if(s.y>H){s.y=0;s.x=Math.random()*W}});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.t-=dt});particles=particles.filter(p=>p.t>0);shake=Math.max(0,shake-dt*12);if(state!=='play')return;stageTime+=dt;bannerTime-=dt;player.inv-=dt;
if(player.dead>0){player.dead-=dt;if(player.dead<=0){player.x=240;player.inv=3}}else{let dir=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0);player.x=clamp(player.x+dir*270*dt,player.dual?30:16,player.dual?W-30:W-16);fireTime-=dt;if(keys.has('Space')&&fireTime<=0){fire();fireTime=.18}}
for(const e of foes){e.t+=dt;if(e.mode==='waiting'){if(stageTime>=e.delay){e.mode='enter';e.t=0}continue}if(e.mode==='gone')continue;
const home=formation(e);
if(e.mode==='enter'){const t=e.t;if(bonus){e.x=240+Math.sin(t*2.1+e.id*.13)*190;e.y=-40+t*150;e.angle=Math.sin(t*2.1)*.8;if(e.y>H+40)e.mode='gone'}else{const p=clamp(t/2.5,0,1),ease=1-Math.pow(1-p,2);e.x=(e.side<0?-70:550)*(1-ease)+home.x*ease+Math.sin(p*Math.PI*2)*95*(1-p);e.y=-40+(home.y+40)*ease+Math.sin(p*Math.PI)*180;e.angle=Math.cos(p*Math.PI*2)*(1-p);if(p===1){e.mode='formation';e.angle=0;e.diving=false}}}
else if(e.mode==='formation'){e.x=home.x;e.y=home.y;e.angle=0}
else if(e.mode==='dive'){const t=e.t;const speed=125+Math.min(stage*5,65);e.y=e.sy+t*speed;e.x=clamp(e.sx+(e.target-e.sx)*Math.min(t/2,1)+Math.sin(t*3)*65,18,W-18);e.angle=Math.sin(t*3)*.7;if(!e.shot&&t>1.2&&!bonus){aim(e);e.shot=true}if(e.y>H+35){e.mode='return';e.t=0;e.x=home.x;e.y=-35}}
else if(e.mode==='return'){e.y+=160*dt;e.angle=0;if(e.y>=home.y){e.mode='formation';e.diving=false}}
else if(e.mode==='tractor'){e.angle=0;const p=Math.min(e.t/1.2,1);e.x=e.sx+(e.target-e.sx)*p;e.y=e.sy+(330-e.sy)*p;if(e.t>1.5&&e.t<4.7&&!player.dual&&player.dead<=0&&Math.abs(player.x-e.x)<31&&lives>1&&!captured){captured={boss:e.id};e.carry=true;lives--;player.dead=2;boom(player.x,player.y,'#66f2f7');announce('FIGHTER CAPTURED!',2)}if(e.t>5.3){e.mode='return';e.y=-30;e.diving=false}}
if(e.mode!=='gone'&&Math.abs(e.x-player.x)<(player.dual?36:22)&&Math.abs(e.y-player.y)<22&&player.dead<=0){hurt()}}
attackTime-=dt;if(!bonus&&attackTime<=0){const pool=foes.filter(e=>e.mode==='formation');if(pool.length){const carrier=pool.find(e=>e.carry);const boss=pool.find(e=>e.type==='boss');const e=carrier||((!captured&&!player.dual&&lives>1&&Math.random()<.35)?boss:null)||pool[Math.floor(Math.random()*pool.length)];dive(e,!e.carry&&e.type==='boss'&&!captured&&!player.dual&&lives>1&&Math.random()<.55)}attackTime=Math.max(.5,1.8-stage*.08)}
for(const s of shots){s.y-=460*dt;for(const e of foes){if(!['gone','waiting'].includes(e.mode)&&Math.abs(s.x-e.x)<16&&Math.abs(s.y-e.y)<15){hit(e);s.y=-100;break}}}shots=shots.filter(s=>s.y>-20);
for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(player.dead<=0&&Math.abs(b.x-player.x)<(player.dual?29:10)&&Math.abs(b.y-player.y)<12){hurt();b.y=H+20}}bullets=bullets.filter(b=>b.y<H+10&&b.x>-10&&b.x<W+10);
if(foes.every(e=>e.mode==='gone')){if(clearTimer===0){clearTimer=3.5;if(bonus){const reward=bonusHits===40?10000:bonusHits*100;addScore(reward);announce(`${bonusHits===40?'PERFECT!':`HITS ${bonusHits} / 40`}  BONUS ${reward}`,3.4)}else announce('STAGE CLEAR',2)}else{clearTimer-=dt;if(clearTimer<=0){stage++;wave()}}}}
function label(text,x,y,color='#eff4fc',size=16,align='center'){ctx.fillStyle=color;ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillText(text,x,y)}
function draw(){ctx.fillStyle='#010207';ctx.fillRect(0,0,W,H);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);for(const s of stars){ctx.fillStyle=s.color;ctx.globalAlpha=.5+Math.sin(clock*2+s.x)*.3;ctx.fillRect(s.x,s.y,s.s>1.2?2:1,2)}ctx.globalAlpha=1;
label('1UP',56,25,'#ef565e',15);label(String(score).padStart(6,'0'),56,47);label('HIGH SCORE',240,25,'#ef565e',15);label(String(best).padStart(6,'0'),240,47);label(`STAGE ${stage}`,422,25,'#f9cc69',14);label(bonus?'BONUS':'READY',422,46,'#94a3b8',12);
if(state==='title'){for(let i=0;i<24;i++)sprite(ctx,i<8?'boss':i<16?'butterfly':'bee',92+(i%8)*42,110+Math.floor(i/8)*38,2.7);sprite(ctx,'ship',240,575,3)}else{for(const e of foes){if(['gone','waiting'].includes(e.mode))continue;if(e.mode==='tractor'&&e.t>1.5&&e.t<4.7){ctx.fillStyle=`rgba(55,224,211,${.1+Math.sin(clock*20)*.035})`;ctx.beginPath();ctx.moveTo(e.x-8,e.y+10);ctx.lineTo(e.x-55,600);ctx.lineTo(e.x+55,600);ctx.lineTo(e.x+8,e.y+10);ctx.fill();ctx.strokeStyle='#4dc4d077';for(let y=e.y+20+(clock*65)%24;y<600;y+=24){ctx.beginPath();ctx.moveTo(e.x-(y-e.y)*.17,y);ctx.lineTo(e.x+(y-e.y)*.17,y);ctx.stroke()}}sprite(ctx,e.type,e.x,e.y,3,e.angle,e.type==='boss'&&e.hp===1);if(e.carry)sprite(ctx,'ship',e.x,e.y-30,2.7,Math.PI)}
if(player&&player.dead<=0&&(player.inv<=0||Math.floor(clock*12)%2===0)){for(const dx of player.dual?[-14,14]:[0])sprite(ctx,'ship',player.x+dx,player.y,3)}
ctx.fillStyle='#faf2a0';shots.forEach(s=>ctx.fillRect(s.x-2,s.y-9,4,13));ctx.fillStyle='#fa7a88';bullets.forEach(b=>ctx.fillRect(b.x-2,b.y-4,4,9));}
for(const p of particles){ctx.globalAlpha=Math.min(1,p.t*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;
for(let i=0;i<Math.min(6,Math.max(0,lives-1));i++)sprite(ctx,'ship',22+i*25,621,1.8);if(lives>7)label(`+${lives-7}`,185,626,'#fff',12);label(`LEVEL ${String(stage).padStart(2,'0')}`,W-18,626,'#f7cc62',12,'right');if(bannerTime>0&&state==='play')label(banner,240,385,'#70edeb',banner.length>25?16:20);ctx.restore()}
function pause(){if(state==='play'){state='paused';msg.textContent='PAUSED\n잠시 쉬어도 괜찮습니다.';start.textContent='계속하기 ↗';overlay.hidden=false;keys.clear();document.querySelector('#pause').textContent='계속하기'}else if(state==='paused'){state='play';overlay.hidden=true;document.querySelector('#pause').textContent='일시정지'}}
function toggleSound(){muted=!muted;document.querySelector('#sound').textContent=`사운드 ${muted?'OFF':'ON'}`;document.querySelector('#sound').setAttribute('aria-pressed',String(!muted));if(!muted)sound()}
start.onclick=()=>state==='paused'?pause():begin();document.querySelector('#pause').onclick=pause;document.querySelector('#sound').onclick=toggleSound;
window.addEventListener('keydown',e=>{if(['Space','ArrowLeft','ArrowRight','Enter'].includes(e.code))e.preventDefault();if(e.repeat){keys.add(e.code);return}if(e.code==='Enter'&&(state==='title'||state==='over'))begin();else if(e.code==='KeyP'||e.code==='Escape')pause();else if(e.code==='KeyM')toggleSound();keys.add(e.code)});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(state==='play')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause()});
for(const [id,key]of [['left','ArrowLeft'],['right','ArrowRight'],['fire','Space']]){const b=document.querySelector('#'+id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(key))}
let drag=false;canvas.addEventListener('pointerdown',e=>{if(state!=='play')return;drag=true;canvas.setPointerCapture(e.pointerId);move(e);keys.add('Space')});function move(e){if(!drag||!player)return;const r=canvas.getBoundingClientRect();player.x=clamp((e.clientX-r.left)/r.width*W,player.dual?30:16,player.dual?W-30:W-16)}canvas.addEventListener('pointermove',move);for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{drag=false;keys.delete('Space')});
let last=0;function frame(t){const dt=Math.min((t-last)/1000||0,.04);last=t;if(state!=='paused')update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();
